// https://github.com/GeeTwentyFive/fpmlinalg
/*
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#pragma once

#include <fpm/fixed.hpp>
#include <fpm/math.hpp>

#include <stdint.h>


namespace fpmlinalg { struct Vec3; struct Quat; inline Quat QuatFromAxisAngle(Vec3 axis, fpm::fixed_16_16 angle); struct Vec4; struct Mat4; inline Mat4 MatrixIdentity(); inline Mat4 MatrixTranslate(fpm::fixed_16_16 x, fpm::fixed_16_16 y, fpm::fixed_16_16 z); inline Mat4 MatrixScale(fpm::fixed_16_16 x, fpm::fixed_16_16 y, fpm::fixed_16_16 z);
struct Vec3 {
        fpm::fixed_16_16 x, y, z;
        Vec3(fpm::fixed_16_16 x, fpm::fixed_16_16 y, fpm::fixed_16_16 z) : x(x), y(y), z(z) {}
        Vec3(int32_t x, int32_t y, int32_t z) { this->x = fpm::fixed_16_16{x}; this->y = fpm::fixed_16_16{y}; this->z = fpm::fixed_16_16{z}; }
        Vec3 operator+(const Vec3& v2) const {return Vec3{x+v2.x, y+v2.y, z+v2.z};}
        Vec3& operator+=(const Vec3& v2) {x+=v2.x; y+=v2.y; z+=v2.z; return *this;}
        Vec3 operator-(const Vec3& v2) const {return Vec3{x-v2.x, y-v2.y, z-v2.z};}
        Vec3& operator-=(const Vec3& v2) {x-=v2.x; y-=v2.y; z-=v2.z; return *this;}
        Vec3 operator-() const {return Vec3{-x, -y, -z};}
        Vec3 operator/(const fpm::fixed_16_16& scalar) const {return Vec3{x/scalar, y/scalar, z/scalar};}
        Vec3& operator/=(const fpm::fixed_16_16& scalar) {x/=scalar; y/=scalar; z/=scalar; return *this;}
        Vec3 operator*(const fpm::fixed_16_16& scalar) const {return Vec3{x*scalar, y*scalar, z*scalar};}
        Vec3& operator*=(const fpm::fixed_16_16& scalar) {x*=scalar; y*=scalar; z*=scalar; return *this;}
        bool operator==(const Vec3& v2) const {return x==v2.x && y==v2.y && z == v2.z;}
        bool operator!=(const Vec3& v2) const {return x!=v2.x || y!=v2.y || z != v2.z;}
        fpm::fixed_16_16 Dot(const Vec3& v2) const {return x*v2.x + y*v2.y + z*v2.z;}
        Vec3 Cross(const Vec3& v2) const {return Vec3{
                y*v2.z - z*v2.y,
                z*v2.x - x*v2.z,
                x*v2.y - y*v2.x
        };}
        fpm::fixed_16_16 LengthSquared() const {return x*x + y*y + z*z;}
        fpm::fixed_16_16 Length() const {return fpm::sqrt(x*x + y*y + z*z);}
        fpm::fixed_16_16 Angle(const Vec3& v2) const {return fpm::atan2(this->Cross(v2).Length(), this->Dot(v2));}
        Vec3 Normalized() const {fpm::fixed_16_16 l = Length(); if (l == fpm::fixed_16_16{0}) l = fpm::fixed_16_16{1}; return Vec3{x/l, y/l, z/l};}
        Vec3 Orthonormalized(const Vec3& v2) const {
                Vec3 v1n = this->Normalized();
                Vec3 v2p = v2 - v1n*v2.Dot(v1n);
                if (v2p.LengthSquared() == fpm::fixed_16_16{0}) {Vec3 fallback = (fpm::abs(v1n.x) < fpm::abs(v1n.y)) ? Vec3{1, 0, 0} : Vec3{0, 1, 0}; v2p = fallback - v1n*fallback.Dot(v1n);}
                return v2p.Normalized().Cross(v1n);
        }
        Vec3 Project(const Vec3& v2) const {return v2 * (this->Dot(v2) / v2.LengthSquared());}
        Vec3 Reflect(const Vec3& normal) const {return *this - (normal * fpm::fixed_16_16{2} * this->Dot(normal));}
};

struct Vec4 { // To interface with Mat4 (w)
        fpm::fixed_16_16 x, y, z, w;
        Vec4(fpm::fixed_16_16 x, fpm::fixed_16_16 y, fpm::fixed_16_16 z, fpm::fixed_16_16 w) : x(x), y(y), z(z), w(w) {}
        Vec4(int32_t x, int32_t y, int32_t z, int32_t w) { this->x = fpm::fixed_16_16{x}; this->y = fpm::fixed_16_16{y}; this->z = fpm::fixed_16_16{z}; this->w = fpm::fixed_16_16{w}; }
};

struct Mat4 { // Column-major
        fpm::fixed_16_16 v[16];
        Mat4(
                fpm::fixed_16_16 c00, fpm::fixed_16_16 c01, fpm::fixed_16_16 c02, fpm::fixed_16_16 c03,
                fpm::fixed_16_16 c10, fpm::fixed_16_16 c11, fpm::fixed_16_16 c12, fpm::fixed_16_16 c13,
                fpm::fixed_16_16 c20, fpm::fixed_16_16 c21, fpm::fixed_16_16 c22, fpm::fixed_16_16 c23,
                fpm::fixed_16_16 c30, fpm::fixed_16_16 c31, fpm::fixed_16_16 c32, fpm::fixed_16_16 c33
        ) {
                v[0] = c00; v[1] = c01; v[2] = c02; v[3] = c03;
                v[4] = c10; v[5] = c11; v[6] = c12; v[7] = c13;
                v[8] = c20; v[9] = c21; v[10] = c22; v[11] = c23;
                v[12] = c30; v[13] = c31; v[14] = c32; v[15] = c33;
        }
        Mat4(
                int32_t c00, int32_t c01, int32_t c02, int32_t c03,
                int32_t c10, int32_t c11, int32_t c12, int32_t c13,
                int32_t c20, int32_t c21, int32_t c22, int32_t c23,
                int32_t c30, int32_t c31, int32_t c32, int32_t c33
        ) {
                v[0] = fpm::fixed_16_16{c00}; v[1] = fpm::fixed_16_16{c01}; v[2] = fpm::fixed_16_16{c02}; v[3] = fpm::fixed_16_16{c03};
                v[4] = fpm::fixed_16_16{c10}; v[5] = fpm::fixed_16_16{c11}; v[6] = fpm::fixed_16_16{c12}; v[7] = fpm::fixed_16_16{c13};
                v[8] = fpm::fixed_16_16{c20}; v[9] = fpm::fixed_16_16{c21}; v[10] = fpm::fixed_16_16{c22}; v[11] = fpm::fixed_16_16{c23};
                v[12] = fpm::fixed_16_16{c30}; v[13] = fpm::fixed_16_16{c31}; v[14] = fpm::fixed_16_16{c32}; v[15] = fpm::fixed_16_16{c33};
        }
        Mat4 operator+(const Mat4& m2) const {return Mat4{
                v[0] + m2.v[0], v[4] + m2.v[4], v[8] + m2.v[8], v[12] + m2.v[12],
                v[1] + m2.v[1], v[5] + m2.v[5], v[9] + m2.v[9], v[13] + m2.v[13],
                v[2] + m2.v[2], v[6] + m2.v[6], v[10] + m2.v[10], v[14] + m2.v[14],
                v[3] + m2.v[3], v[7] + m2.v[7], v[11] + m2.v[11], v[15] + m2.v[15]
        };}
        Mat4 operator*(const fpm::fixed_16_16& scalar) const {return Mat4{
                v[0]*scalar, v[4]*scalar, v[8]*scalar, v[12]*scalar,
                v[1]*scalar, v[5]*scalar, v[9]*scalar, v[13]*scalar,
                v[2]*scalar, v[6]*scalar, v[10]*scalar, v[14]*scalar,
                v[3]*scalar, v[7]*scalar, v[11]*scalar, v[15]*scalar
        };}
        Vec4 operator*(const Vec4& vec) const {return Vec4{
                vec.x*v[0] + vec.y*v[4] + vec.z*v[8] + vec.w*v[12],
                vec.x*v[1] + vec.y*v[5] + vec.z*v[9] + vec.w*v[13],
                vec.x*v[2] + vec.y*v[6] + vec.z*v[10] + vec.w*v[14],
                vec.x*v[3] + vec.y*v[7] + vec.z*v[11] + vec.w*v[15]
        };}
        Mat4 operator*(const Mat4& m2) const {return Mat4{
                v[0]*m2.v[0] + v[4]*m2.v[1] + v[8]*m2.v[2] + v[12]*m2.v[3],
                v[1]*m2.v[0] + v[5]*m2.v[1] + v[9]*m2.v[2] + v[13]*m2.v[3],
                v[2]*m2.v[0] + v[6]*m2.v[1] + v[10]*m2.v[2] + v[14]*m2.v[3],
                v[3]*m2.v[0] + v[7]*m2.v[1] + v[11]*m2.v[2] + v[15]*m2.v[3],
                v[0]*m2.v[4] + v[4]*m2.v[5] + v[8]*m2.v[6] + v[12]*m2.v[7],
                v[1]*m2.v[4] + v[5]*m2.v[5] + v[9]*m2.v[6] + v[13]*m2.v[7],
                v[2]*m2.v[4] + v[6]*m2.v[5] + v[10]*m2.v[6] + v[14]*m2.v[7],
                v[3]*m2.v[4] + v[7]*m2.v[5] + v[11]*m2.v[6] + v[15]*m2.v[7],
                v[0]*m2.v[8] + v[4]*m2.v[9] + v[8]*m2.v[10] + v[12]*m2.v[11],
                v[1]*m2.v[8] + v[5]*m2.v[9] + v[9]*m2.v[10] + v[13]*m2.v[11],
                v[2]*m2.v[8] + v[6]*m2.v[9] + v[10]*m2.v[10] + v[14]*m2.v[11],
                v[3]*m2.v[8] + v[7]*m2.v[9] + v[11]*m2.v[10] + v[15]*m2.v[11],
                v[0]*m2.v[12] + v[4]*m2.v[13] + v[8]*m2.v[14] + v[12]*m2.v[15],
                v[1]*m2.v[12] + v[5]*m2.v[13] + v[9]*m2.v[14] + v[13]*m2.v[15],
                v[2]*m2.v[12] + v[6]*m2.v[13] + v[10]*m2.v[14] + v[14]*m2.v[15],
                v[3]*m2.v[12] + v[7]*m2.v[13] + v[11]*m2.v[14] + v[15]*m2.v[15]
        };}
        Mat4 Transposed() const {return Mat4{
                v[0], v[4], v[8], v[12],
                v[1], v[5], v[9], v[13],
                v[2], v[6], v[10], v[14],
                v[3], v[7], v[11], v[15]
        };}
        Mat4 Inverted() const {
                Mat4 out{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};

                fpm::fixed_16_16 a00 = v[0], a01 = v[1], a02 = v[2], a03 = v[3];
                fpm::fixed_16_16 a10 = v[4], a11 = v[5], a12 = v[6], a13 = v[7];
                fpm::fixed_16_16 a20 = v[8], a21 = v[9], a22 = v[10], a23 = v[11];
                fpm::fixed_16_16 a30 = v[12], a31 = v[13], a32 = v[14], a33 = v[15];

                fpm::fixed_16_16 b00 = a00*a11 - a01*a10;
                fpm::fixed_16_16 b01 = a00*a12 - a02*a10;
                fpm::fixed_16_16 b02 = a00*a13 - a03*a10;
                fpm::fixed_16_16 b03 = a01*a12 - a02*a11;
                fpm::fixed_16_16 b04 = a01*a13 - a03*a11;
                fpm::fixed_16_16 b05 = a02*a13 - a03*a12;
                fpm::fixed_16_16 b06 = a20*a31 - a21*a30;
                fpm::fixed_16_16 b07 = a20*a32 - a22*a30;
                fpm::fixed_16_16 b08 = a20*a33 - a23*a30;
                fpm::fixed_16_16 b09 = a21*a32 - a22*a31;
                fpm::fixed_16_16 b10 = a21*a33 - a23*a31;
                fpm::fixed_16_16 b11 = a22*a33 - a23*a32;

                fpm::fixed_16_16 det = b00*b11 - b01*b10 + b02*b09 + b03*b08 - b04*b07 + b05*b06;
                if (det == fpm::fixed_16_16{0}) return MatrixIdentity();

                out.v[0] = (a11*b11 - a12*b10 + a13*b09) / det;
                out.v[1] = (-a01*b11 + a02*b10 - a03*b09) / det;
                out.v[2] = (a31*b05 - a32*b04 + a33*b03) / det;
                out.v[3] = (-a21*b05 + a22*b04 - a23*b03) / det;
                out.v[4] = (-a10*b11 + a12*b08 - a13*b07) / det;
                out.v[5] = (a00*b11 - a02*b08 + a03*b07) / det;
                out.v[6] = (-a30*b05 + a32*b02 - a33*b01) / det;
                out.v[7] = (a20*b05 - a22*b02 + a23*b01) / det;
                out.v[8] = (a10*b10 - a11*b08 + a13*b06) / det;
                out.v[9] = (-a00*b10 + a01*b08 - a03*b06) / det;
                out.v[10] = (a30*b04 - a31*b02 + a33*b00) / det;
                out.v[11] = (-a20*b04 + a21*b02 - a23*b00) / det;
                out.v[12] = (-a10*b09 + a11*b07 - a12*b06) / det;
                out.v[13] = (a00*b09 - a01*b07 + a02*b06) / det;
                out.v[14] = (-a30*b03 + a31*b01 - a32*b00) / det;
                out.v[15] = (a20*b03 - a21*b01 + a22*b00) / det;

                return out;
        }
};
inline Mat4 MatrixIdentity() {return Mat4{
        1, 0, 0, 0,
        0, 1, 0, 0,
        0, 0, 1, 0,
        0, 0, 0, 1
};}
inline Mat4 MatrixTranslate(fpm::fixed_16_16 x, fpm::fixed_16_16 y, fpm::fixed_16_16 z) {return Mat4{
        fpm::fixed_16_16{1}, fpm::fixed_16_16{0}, fpm::fixed_16_16{0}, fpm::fixed_16_16{0},
        fpm::fixed_16_16{0}, fpm::fixed_16_16{1}, fpm::fixed_16_16{0}, fpm::fixed_16_16{0},
        fpm::fixed_16_16{0}, fpm::fixed_16_16{0}, fpm::fixed_16_16{1}, fpm::fixed_16_16{0},
        x, y, z, fpm::fixed_16_16{1}
};}
inline Mat4 MatrixScale(fpm::fixed_16_16 x, fpm::fixed_16_16 y, fpm::fixed_16_16 z) {return Mat4{
        x, fpm::fixed_16_16{0}, fpm::fixed_16_16{0}, fpm::fixed_16_16{0},
        fpm::fixed_16_16{0}, y, fpm::fixed_16_16{0}, fpm::fixed_16_16{0},
        fpm::fixed_16_16{0}, fpm::fixed_16_16{0}, z, fpm::fixed_16_16{0},
        fpm::fixed_16_16{0}, fpm::fixed_16_16{0}, fpm::fixed_16_16{0}, fpm::fixed_16_16{1}
};}

struct Quat {
        fpm::fixed_16_16 x, y, z, w;
        Quat(fpm::fixed_16_16 x, fpm::fixed_16_16 y, fpm::fixed_16_16 z, fpm::fixed_16_16 w) : x(x), y(y), z(z), w(w) {}
        Quat(int32_t x, int32_t y, int32_t z, int32_t w) { this->x = fpm::fixed_16_16{x}; this->y = fpm::fixed_16_16{y}; this->z = fpm::fixed_16_16{z}; this->w = fpm::fixed_16_16{w}; }
        Quat operator*(const Quat& q2) const {return Quat{
                x*q2.w + w*q2.x + y*q2.z - z*q2.y,
                y*q2.w + w*q2.y + z*q2.x - x*q2.z,
                z*q2.w + w*q2.z + x*q2.y - y*q2.x,
                w*q2.w - x*q2.x - y*q2.y - z*q2.z
        };}
        fpm::fixed_16_16 Dot(const Quat& q2) const {return x*q2.x + y*q2.y + z*q2.z + w*q2.w;}
        fpm::fixed_16_16 LengthSquared() const {return x*x + y*y + z*z + w*w;}
        fpm::fixed_16_16 Length() const {return fpm::sqrt(x*x + y*y + z*z + w*w);}
        Quat Normalized() const {fpm::fixed_16_16 l = Length(); if (l == fpm::fixed_16_16{0}) l = fpm::fixed_16_16{1}; return Quat{x/l, y/l, z/l, w/l};}
        Quat Inverted() const {fpm::fixed_16_16 l = LengthSquared(); if (l == fpm::fixed_16_16{0}) l = fpm::fixed_16_16{1}; return Quat{-x/l, -y/l, -z/l, w/l};}
        Quat NLerp(const Quat& to, fpm::fixed_16_16 amount) {return Quat{
                x + amount*(to.x - x),
                y + amount*(to.y - y),
                z + amount*(to.z - z),
                w + amount*(to.w - w)
        }.Normalized();}
        Vec3 Rotate(const Vec3& v) const {Quat q = Normalized(); return Vec3{
                v.x*(q.x*q.x + q.w*q.w - q.y*q.y - q.z*q.z) + v.y*(2*q.x*q.y - 2*q.w*q.z) + v.z*(2*q.x*q.z + 2*q.w*q.y),
                v.x*(2*q.w*q.z + 2*q.x*q.y) + v.y*(q.w*q.w - q.x*q.x + q.y*q.y - q.z*q.z) + v.z*(-2*q.w*q.x + 2*q.y*q.z),
                v.x*(-2*q.w*q.y + 2*q.x*q.z) + v.y*(2*q.w*q.x + 2*q.y*q.z)+ v.z*(q.w*q.w - q.x*q.x - q.y*q.y + q.z*q.z)
        };}
        Mat4 ToMatrix() const { Quat q = Normalized();
                Mat4 out = MatrixIdentity();
                out.v[0] = fpm::fixed_16_16{1} - fpm::fixed_16_16{2}*(q.y*q.y + q.z*q.z);
                out.v[1] = fpm::fixed_16_16{2}*(q.x*q.y + q.z*q.w);
                out.v[2] = fpm::fixed_16_16{2}*(q.x*q.z - q.y*q.w);
                out.v[4] = fpm::fixed_16_16{2}*(q.x*q.y - q.z*q.w);
                out.v[5] = fpm::fixed_16_16{1} - fpm::fixed_16_16{2}*(q.x*q.x + q.z*q.z);
                out.v[6] = fpm::fixed_16_16{2}*(q.y*q.z + q.x*q.w);
                out.v[8] = fpm::fixed_16_16{2}*(q.x*q.z + q.y*q.w);
                out.v[9] = fpm::fixed_16_16{2}*(q.y*q.z - q.x*q.w);
                out.v[10] = fpm::fixed_16_16{1} - fpm::fixed_16_16{2}*(q.x*q.x + q.y*q.y);
                return out;
        }
};
inline Quat QuatFromAxisAngle(Vec3 axis, fpm::fixed_16_16 angle) {
        Quat out = {0, 0, 0, 1}; if (axis.LengthSquared() == fpm::fixed_16_16{0}) return out;
        axis = axis.Normalized();
        fpm::fixed_16_16 sin_angle = fpm::sin(angle/2);
        out.x = axis.x * sin_angle; out.y = axis.y * sin_angle; out.z = axis.z * sin_angle;
        out.w = fpm::cos(angle/2);
        return out.Normalized();
}
}