// https://github.com/GeeTwentyFive/GCollision
/*
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#pragma once

#include <fpmlinalg.hpp>

namespace gcollision {
typedef struct {
        fpmlinalg::Vec3 min;
        fpmlinalg::Vec3 max;
} AABB;
bool IntersectAABBs(const AABB& a, const AABB& b) {return (
        (a.min.x <= b.max.x && a.max.x >= b.min.x) &&
        (a.min.y <= b.max.y && a.max.y >= b.min.y) &&
        (a.min.z <= b.max.z && a.max.z >= b.min.z)
);}

typedef struct {
        bool hit = false;
        fpm::fixed_16_16 distance = fpm::fixed_16_16{0};
        fpmlinalg::Vec3 point = fpmlinalg::Vec3{0, 0, 0};
        fpmlinalg::Vec3 normal = fpmlinalg::Vec3{0, 0, 0};
} RayHitInfo;
RayHitInfo IntersectRayAABB(
        const fpmlinalg::Vec3& ray_origin,
        fpmlinalg::Vec3 ray_direction,
        const AABB& target
) {
        RayHitInfo hit_info{};

        if (ray_direction.x == fpm::fixed_16_16{0} && (ray_origin.x < target.min.x || ray_origin.x > target.max.x)) { hit_info.hit = false; return hit_info; }
        if (ray_direction.y == fpm::fixed_16_16{0} && (ray_origin.y < target.min.y || ray_origin.y > target.max.y)) { hit_info.hit = false; return hit_info; }
        if (ray_direction.z == fpm::fixed_16_16{0} && (ray_origin.z < target.min.z || ray_origin.z > target.max.z)) { hit_info.hit = false; return hit_info; }

        bool inside_box = (
                (ray_origin.x > target.min.x && ray_origin.x < target.max.x) &&
                (ray_origin.y > target.min.y && ray_origin.y < target.max.y) &&
                (ray_origin.z > target.min.z && ray_origin.z < target.max.z)
        );

        //if (inside_box) ray_direction = -ray_direction;  // (apparently not needed...?)

        fpm::fixed_16_16 t_min_x, t_max_x;
        if (ray_direction.x == fpm::fixed_16_16{0}) {
                t_min_x = fpm::fixed_16_16{-32768};
                t_max_x = fpm::fixed_16_16{32767};
        } else {
                t_min_x = (target.min.x - ray_origin.x) / ray_direction.x;
                t_max_x = (target.max.x - ray_origin.x) / ray_direction.x;
        }

        fpm::fixed_16_16 t_min_y, t_max_y;
        if (ray_direction.y == fpm::fixed_16_16{0}) {
                t_min_y = fpm::fixed_16_16{-32768};
                t_max_y = fpm::fixed_16_16{32767};
        } else {
                t_min_y = (target.min.y - ray_origin.y) / ray_direction.y;
                t_max_y = (target.max.y - ray_origin.y) / ray_direction.y;
        }

        fpm::fixed_16_16 t_min_z, t_max_z;
        if (ray_direction.z == fpm::fixed_16_16{0}) {
                t_min_z = fpm::fixed_16_16{-32768};
                t_max_z = fpm::fixed_16_16{32767};
        } else {
                t_min_z = (target.min.z - ray_origin.z) / ray_direction.z;
                t_max_z = (target.max.z - ray_origin.z) / ray_direction.z;
        }

        static auto MAX = [](fpm::fixed_16_16 a, fpm::fixed_16_16 b) { return (a > b) ? a : b; };
        static auto MIN = [](fpm::fixed_16_16 a, fpm::fixed_16_16 b) { return (a < b) ? a : b; };
        fpm::fixed_16_16 t_min = MAX( MAX(MIN(t_min_x, t_max_x), MIN(t_min_y, t_max_y)),  MIN(t_min_z, t_max_z) );
        fpm::fixed_16_16 t_max = MIN( MIN(MAX(t_min_x, t_max_x), MAX(t_min_y, t_max_y)),  MAX(t_min_z, t_max_z) );

        if (
                (t_max < fpm::fixed_16_16{0}) ||  // AABB behind ray
                (t_min > t_max)  // No hit
        ) { hit_info.hit = false; return hit_info; }

        hit_info.hit = true;
        hit_info.distance = (t_min < fpm::fixed_16_16{0}) ? t_max : t_min;
        hit_info.point = ray_origin + (ray_direction * hit_info.distance);
        hit_info.normal = fpmlinalg::Vec3{0, 0, 0};
        if (t_min_x == t_min || t_max_x == t_min) hit_info.normal.x = (ray_direction.x > fpm::fixed_16_16{0}) ? fpm::fixed_16_16{-1} : fpm::fixed_16_16{1};
        else if (t_min_y == t_min || t_max_y == t_min) hit_info.normal.y = (ray_direction.y > fpm::fixed_16_16{0}) ? fpm::fixed_16_16{-1} : fpm::fixed_16_16{1};
        else hit_info.normal.z = (ray_direction.z > fpm::fixed_16_16{0}) ? fpm::fixed_16_16{-1} : fpm::fixed_16_16{1};

        if (inside_box) { //ray_direction = -ray_direction;
                hit_info.distance = -hit_info.distance;
                hit_info.normal = -hit_info.normal;
        }

        return hit_info;
}
}