// https://github.com/GeeTwentyFive/GPhysics
/*
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#pragma once

#include <fpm/fixed.hpp>
#include <fpm/math.hpp>
#include <fpmlinalg.hpp>
#include <GCollision.hpp>

#include <vector>
#include <stdint.h>

class GPhysics { public: struct Box; private: uint64_t _uid = 0; public: inline uint64_t _NewUID() {return _uid++;}
        std::vector<GPhysics::Box> boxes;
        fpm::fixed_16_16 tickrate = fpm::fixed_16_16{128};  // Must never be 0

        uint16_t max_boxes;
        GPhysics(uint16_t max_boxes = 8192) : max_boxes(max_boxes) { boxes.reserve(max_boxes); };

        struct Box {
                void* user_data;
                GPhysics* physics_instance = nullptr; uint64_t _id;
                bool dynamic = false;
                bool lock_x = false, lock_y = false, lock_z = false;
                bool in_air = true;
                gcollision::AABB aabb = gcollision::AABB{fpmlinalg::Vec3{0, 0, 0}, fpmlinalg::Vec3{0, 0, 0}};
                fpmlinalg::Vec3 velocity = fpmlinalg::Vec3{0, 0, 0};
                fpm::fixed_16_16 gravity = fpm::fixed_16_16::from_custom_fraction<100>(-9, 81);
                fpm::fixed_16_16 friction = fpm::fixed_16_16{1};
                fpm::fixed_16_16 bounciness = fpm::fixed_16_16{1}/fpm::fixed_16_16{8};
                fpmlinalg::Vec3 GetPosition() const {fpmlinalg::Vec3 mm = aabb.min + aabb.max; return fpmlinalg::Vec3{mm.x/2, mm.y/2, mm.z/2};};
                void SetPosition(fpmlinalg::Vec3 new_pos) { fpmlinalg::Vec3 size = aabb.max - aabb.min;
                        fpmlinalg::Vec3 half_extent = fpmlinalg::Vec3{size.x/2, size.y/2, size.z/2};
                        this->aabb.min = new_pos - half_extent;
                        this->aabb.max = new_pos + half_extent;
                };
                void ApplyForce(fpmlinalg::Vec3 f) { this->velocity += ((f / physics_instance->tickrate) / (1 + (velocity.Length() / physics_instance->tickrate))); };
                void Remove() { for (auto it = this->physics_instance->boxes.begin(); it != this->physics_instance->boxes.end(); it++) { if (it->_id == this->_id) {this->physics_instance->boxes.erase(it); return;} }; }
        };
        Box* AddBox(fpmlinalg::Vec3 size) { if (boxes.size() >= max_boxes) return nullptr;
                Box box{};
                box.physics_instance = this; box._id = this->_NewUID();
                box.aabb.min = -fpmlinalg::Vec3{size.x/2, size.y/2, size.z/2};
                box.aabb.max = fpmlinalg::Vec3{size.x/2, size.y/2, size.z/2};
                this->boxes.push_back(box);
                return &boxes.back();
        }

        void Tick() { for (size_t i = 0; i < boxes.size(); i++) {
                Box& b = boxes[i];

                if (!b.dynamic) continue;

                if (b.in_air) b.ApplyForce(fpmlinalg::Vec3{fpm::fixed_16_16{0}, b.gravity, fpm::fixed_16_16{0}});
                else b.velocity *= 1-(b.friction/tickrate);

                fpmlinalg::Vec3 new_position = b.GetPosition() + b.velocity/tickrate;
                gcollision::AABB new_aabb = b.aabb;
                fpmlinalg::Vec3 new_aabb_size = new_aabb.max - new_aabb.min;
                fpmlinalg::Vec3 new_aabb_half_extent = fpmlinalg::Vec3{new_aabb_size.x/2, new_aabb_size.y/2, new_aabb_size.z/2};
                new_aabb.min = new_position - new_aabb_half_extent;
                new_aabb.max = new_position + new_aabb_half_extent;

                b.in_air = true;
                for (size_t j = i+1; j < boxes.size(); j++) {
                        Box& b2 = boxes[j];

                        if ((new_position - b.GetPosition()).LengthSquared() != fpm::fixed_16_16{0}) { gcollision::RayHitInfo hit_info = gcollision::IntersectRayAABB(
                                b.GetPosition(),
                                (new_position - b.GetPosition()),
                                b2.aabb
                        ); if (hit_info.hit) new_position = hit_info.point + (hit_info.normal/tickrate); }

                        if (gcollision::IntersectAABBs(new_aabb, b2.aabb)) {
                                b.in_air = false;

                                // TODO: Collision resolution
                        }
                }

                b.aabb = new_aabb;
        }}
};
