// https://github.com/GeeTwentyFive/GPhysics
/*
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#pragma once

#include <fpm/fixed.hpp>
#include <fpm/math.hpp>
#include <fpmlinalg.hpp>
#include <GCollision.hpp>

#include <memory>
#include <vector>
#include <stdint.h>

class GPhysics { public: struct Box;
        std::vector<std::unique_ptr<GPhysics::Box>> boxes;
        fpm::fixed_16_16 tickrate = fpm::fixed_16_16{128};  // Must never be 0

        uint16_t max_boxes;
        GPhysics(uint16_t max_boxes = 8192) : max_boxes(max_boxes) { boxes.reserve(max_boxes); };

        typedef bool(*CollisionCallback)(Box* collidee);  // Return `false` to ignore collision
        struct Box { void* user_data = nullptr; GPhysics* _physics_instance = nullptr;
                gcollision::AABB aabb = gcollision::AABB{fpmlinalg::Vec3{0, 0, 0}, fpmlinalg::Vec3{0, 0, 0}};
                bool dynamic = false;
                fpmlinalg::Vec3 velocity = fpmlinalg::Vec3{0, 0, 0};
                fpm::fixed_16_16 gravity = fpm::fixed_16_16::from_custom_fraction<100>(-9, 81);
                fpm::fixed_16_16 friction = fpm::fixed_16_16{1};
                fpm::fixed_16_16 bounciness = fpm::fixed_16_16{1}/fpm::fixed_16_16{8};
                CollisionCallback collision_callback = nullptr;  // Is only called for `dynamic` boxes. Return `false` to ignore collision
                void ApplyForce(fpmlinalg::Vec3 f) { this->velocity += ((f / _physics_instance->tickrate) / (1 + (velocity.Length() / _physics_instance->tickrate))); };
                void Remove() { for (auto it = this->_physics_instance->boxes.begin(); it != this->_physics_instance->boxes.end(); it++) { if (it->get() == this) {this->_physics_instance->boxes.erase(it); return;} }; }

                bool currently_colliding = false;  // Is only set for `dynamic` boxes
        };
        Box* AddBox(fpmlinalg::Vec3 size) { if (boxes.size() >= max_boxes) return nullptr;
                auto box = std::make_unique<Box>();
                box->_physics_instance = this;
                box->aabb.min = -(size/fpm::fixed_16_16{2});
                box->aabb.max = size/fpm::fixed_16_16{2};
                Box* ptr = box.get();
                this->boxes.push_back(std::move(box));
                return ptr;
        }

        void Tick() { for (size_t i = 0; i < boxes.size(); i++) {
                Box& b = *boxes[i]; fpm::fixed_16_16 epsilon = fpm::fixed_16_16{1}/tickrate;  // for dealing with near-zero rounding (fixed-point (and floats too) has limited decimal precision after all...)

                if (!b.dynamic) continue;

                if (!b.currently_colliding) b.ApplyForce(fpmlinalg::Vec3{fpm::fixed_16_16{0}, b.gravity, fpm::fixed_16_16{0}});
                else b.velocity *= 1-(b.friction/tickrate);

                if (b.velocity.LengthSquared() < epsilon) continue;  // Don't move nor collide if future speed (aka. velocity) is miniscule (to prevent shakyness/jitter) (minimum speed = sqrt(epsilon))

                fpmlinalg::Vec3 new_position = b.aabb.GetCenterPos() + b.velocity/tickrate;

                b.currently_colliding = false;
                for (size_t j = 0; j < boxes.size(); j++) { if (j == i) continue;
                        Box& b2 = *boxes[j];

                        // // center-raycast Continuous Collision Detection  // TODO: FIX: Implement whole-world return-just-nearest CastRay() and use that here instead
                        // if ((new_position - b.aabb.GetCenterPos()).LengthSquared() > fpm::fixed_16_16{0}) { gcollision::RayHitInfo hit_info = gcollision::IntersectRayAABB(
                        //         b.aabb.GetCenterPos(),
                        //         (new_position - b.aabb.GetCenterPos()),
                        //         b2.aabb
                        // ); if (hit_info.hit) new_position = hit_info.point + (hit_info.normal*epsilon); }

                        // if (distance between box 1 and box 2) > (box 1 size + box 2 size): skip
                        // ^ aka.: If they're too far for collisions to even be possible
                        if ((b2.aabb.GetCenterPos() - new_position).LengthSquared() > (b.aabb.GetSize() + b2.aabb.GetSize()).LengthSquared()) continue;

                        if (b.aabb.Intersects(b2.aabb)) {
                                b.currently_colliding = true;
                                if (b.collision_callback != nullptr) {if (!b.collision_callback(&b2)) continue;}  // Call user's collision callback, ignore collision if user's callback returns `false`

                                fpmlinalg::Vec3 collision_normal = b.aabb.GetCollisionNormal(b2.aabb);
                                fpm::fixed_16_16 collision_depth = b.aabb.GetPenetrationDepth(b2.aabb);

                                fpmlinalg::Vec3 pos_correction = collision_normal;
                                if (b2.dynamic) pos_correction *= (collision_depth+epsilon)/2;
                                else pos_correction *= collision_depth+epsilon;
                                new_position += pos_correction;

                                b.velocity = b.velocity.Reflect(collision_normal) * b.bounciness;
                        }
                }

                b.aabb.SetCenterPos(new_position);
        }}
};
